// <auto-generated />
using System;
using MagicHotel.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicHotel.Migrations
{
    [DbContext(typeof(AplicationDbContextcs))]
    [Migration("20230302064135_AlimentarTablaHotel")]
    partial class AlimentarTablaHotel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MagicHotel.Modelos.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<int>("Tourist")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hoteles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "",
                            FechaInicio = new DateTime(2023, 3, 1, 22, 41, 35, 806, DateTimeKind.Local).AddTicks(1468),
                            FechaUpdate = new DateTime(2023, 3, 1, 22, 41, 35, 806, DateTimeKind.Local).AddTicks(1476),
                            ImagenUrl = "",
                            Name = "Hotel Habana Libre...",
                            SquareMeters = 50,
                            Tarifa = 200.0,
                            Tourist = 5
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "",
                            FechaInicio = new DateTime(2023, 3, 1, 22, 41, 35, 806, DateTimeKind.Local).AddTicks(1478),
                            FechaUpdate = new DateTime(2023, 3, 1, 22, 41, 35, 806, DateTimeKind.Local).AddTicks(1479),
                            ImagenUrl = "",
                            Name = "Hotel Nacional...",
                            SquareMeters = 60,
                            Tarifa = 250.0,
                            Tourist = 3
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "",
                            Detalle = "",
                            FechaInicio = new DateTime(2023, 3, 1, 22, 41, 35, 806, DateTimeKind.Local).AddTicks(1480),
                            FechaUpdate = new DateTime(2023, 3, 1, 22, 41, 35, 806, DateTimeKind.Local).AddTicks(1480),
                            ImagenUrl = "",
                            Name = "Hotel Copacavana...",
                            SquareMeters = 70,
                            Tarifa = 300.0,
                            Tourist = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
